"""empty message

Revision ID: 7c2445c07cc7
Revises:
Create Date: 2025-03-07 14:19:31.549133

"""

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c2445c07cc7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_article",
        sa.Column("id", sa.Integer(), nullable=False, comment="主键"),
        sa.Column("title", sa.String(length=256), nullable=False, comment="标题"),
        sa.Column("category", sa.String(length=256), nullable=False, comment="分类"),
        sa.Column("content", sa.Text(), nullable=False, comment="内容"),
        sa.Column("traffic", sa.Integer(), nullable=False, comment="访问量"),
        sa.Column("comment_num", sa.Integer(), nullable=False, comment="评论数"),
        sa.Column("remark", sa.String(length=256), nullable=True, comment="备注"),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("create_by", sa.String(length=256), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.String(length=256), nullable=False, comment="更新人"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="软删除"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("user_name", sa.String(length=256), nullable=False, comment="用户名"),
        sa.Column("real_name", sa.JSON(), nullable=True, comment="姓名"),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("create_by", sa.String(length=256), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.String(length=256), nullable=False, comment="更新人"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="软删除"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "blog_comment",
        sa.Column("id", sa.Integer(), nullable=False, comment="主键"),
        sa.Column("comment", sa.Text(), nullable=False, comment="评论"),
        sa.Column("blog_id", sa.Integer(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("create_by", sa.String(length=256), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.String(length=256), nullable=False, comment="更新人"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="软删除"),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blog_article.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_comment")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("blog_article")
    # ### end Alembic commands ###
