services:
  api: &main_app
    build:
      context: ..
      dockerfile: ../build/Dockerfile
    image: blog_api:${BLOG_API_VERSION:-latest}
    restart: always
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      BLOG_API_HOST: 0.0.0.0
      BLOG_API_DB_HOST: app-db
      BLOG_API_DB_PORT: 3306
      BLOG_API_DB_USER: app
      BLOG_API_DB_PASS: app
      BLOG_API_DB_BASE: app
      BLOG_API_REDIS_HOST: app-redis

  db:
    image: mysql:8.4
    hostname: app-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
      MYSQL_DATABASE: "app"
      MYSQL_HOST: "0.0.0.0"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - --user=app
        - --password=app
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
      - "app-db-data:/bitnami/mysql/data"

  migrator:
    image: blog_api:${BLOG_API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      BLOG_API_DB_HOST: app-db
      BLOG_API_DB_PORT: 3306
      BLOG_API_DB_USER: app
      BLOG_API_DB_PASS: app
      BLOG_API_DB_BASE: app
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "app-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  blog_api-db-data:
    name: app-db-data
